drop useless default breaks
clang-cl:
```
  In file included from C:\projects\libssh2\_builds\src\CMakeFiles\libssh2_static.dir\Unity\unity_0_c.c:61:
C:/projects/libssh2/src/scp.c(177,13): error : default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default] [C:\projects\libssh2\_builds\src\libssh2_static.vcxproj]
C:/projects/libssh2/src/scp.c(209,13): error : default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default] [C:\projects\libssh2\_builds\src\libssh2_static.vcxproj]
C:/projects/libssh2/src/scp.c(234,13): error : default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default] [C:\projects\libssh2\_builds\src\libssh2_static.vcxproj]
C:/projects/libssh2/src/scp.c(259,5): error : default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default] [C:\projects\libssh2\_builds\src\libssh2_static.vcxproj]
```
https://ci.appveyor.com/project/libssh2org/libssh2/builds/50910997/job/rj8015to7ivll0up#L155