kex: disable macros when unused
```
libssh2/src/kex.c:58: error: macro "LIBSSH2_KEX_METHOD_EC_SHA_VALUE_HASH" is not used [-Werror=unused-macros]
   58 | #define LIBSSH2_KEX_METHOD_EC_SHA_VALUE_HASH(value, reqlen, version)        \
      |
libssh2/src/kex.c:1589: error: macro "LIBSSH2_KEX_METHOD_EC_SHA_HASH_CREATE_VERIFY" is not used [-Werror=unused-macros]
 1589 | #define LIBSSH2_KEX_METHOD_EC_SHA_HASH_CREATE_VERIFY(digest_type)            \
      |
```