Revert "match callback func with prototype 2"
This reverts commit f8153b81d0fce792eb227ea7ec82f08f409b289f.

OpenBSD still has this:
```
In file included from /home/runner/work/libssh2/libssh2/src/crypto.c:10:
/home/runner/work/libssh2/libssh2/src/openssl.c:1251:9: error: cast from 'RSA *(*)(BIO *, RSA **, pem_password_cb *, void *)' (aka 'struct rsa_st *(*)(struct bio_st *, struct rsa_st **, int (*)(char *, int, int, void *), void *)') to 'pem_read_bio_func' (aka 'struct evp_pkey_st *(*)(struct bio_st *, struct evp_pkey_st **, int (*)(char *, int, int, void *), void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        (pem_read_bio_func) &PEM_read_bio_RSAPrivateKey;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/libssh2/libssh2/src/openssl.c:1659:9: error: cast from 'RSA *(*)(BIO *, RSA **, pem_password_cb *, void *)' (aka 'struct rsa_st *(*)(struct bio_st *, struct rsa_st **, int (*)(char *, int, int, void *), void *)') to 'pem_read_bio_func' (aka 'struct evp_pkey_st *(*)(struct bio_st *, struct evp_pkey_st **, int (*)(char *, int, int, void *), void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        (pem_read_bio_func) &PEM_read_bio_RSAPrivateKey;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/libssh2/libssh2/src/openssl.c:2048:9: error: cast from 'EC_KEY *(*)(BIO *, EC_KEY **, pem_password_cb *, void *)' (aka 'struct ec_key_st *(*)(struct bio_st *, struct ec_key_st **, int (*)(char *, int, int, void *), void *)') to 'pem_read_bio_func' (aka 'struct evp_pkey_st *(*)(struct bio_st *, struct evp_pkey_st **, int (*)(char *, int, int, void *), void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        (pem_read_bio_func) &PEM_read_bio_ECPrivateKey;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/libssh2/libssh2/src/openssl.c:4013:9: error: cast from 'EC_KEY *(*)(BIO *, EC_KEY **, pem_password_cb *, void *)' (aka 'struct ec_key_st *(*)(struct bio_st *, struct ec_key_st **, int (*)(char *, int, int, void *), void *)') to 'pem_read_bio_func' (aka 'struct evp_pkey_st *(*)(struct bio_st *, struct evp_pkey_st **, int (*)(char *, int, int, void *), void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        (pem_read_bio_func) &PEM_read_bio_ECPrivateKey;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/libssh2/libssh2/src/openssl.c:4046:9: error: cast from 'EC_KEY *(*)(BIO *, EC_KEY **, pem_password_cb *, void *)' (aka 'struct ec_key_st *(*)(struct bio_st *, struct ec_key_st **, int (*)(char *, int, int, void *), void *)') to 'pem_read_bio_func' (aka 'struct evp_pkey_st *(*)(struct bio_st *, struct evp_pkey_st **, int (*)(char *, int, int, void *), void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        (pem_read_bio_func) &PEM_read_bio_ECPrivateKey;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
https://github.com/libssh2/libssh2/actions/runs/11647740993/job/32433355286#step:3:161