hostkey.c drop unused assignment in hostkey_method_ssh_dss_sig_verify
```
/home/runner/work/libssh2/libssh2/src/hostkey.c:618:5: error: Value stored to 'sig_len' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
  618 |     sig_len -= 15;
      |     ^          ~~
/home/runner/work/libssh2/libssh2/src/hostkey.c:618:5: note: Value stored to 'sig_len' is never read
  618 |     sig_len -= 15;
      |     ^          ~~
```
https://github.com/libssh2/libssh2/actions/runs/28659316347/job/84995915568?pr=2195