fix MSVC fallout
VS2015:
```
tests\test_simple.c(60): error C2220: warning treated as error - no 'object' file generated
tests\test_simple.c(60): warning C4777: 'fprintf' : format string '%d' requires an argument of type 'int', but variadic argument 1 has type 'std::size_t'
tests\test_simple.c(60): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
tests\test_simple.c(60): note: the sizes of types 'std::size_t' and 'int' might differ on other platforms
tests\test_simple.c(60): note: consider using '%zd' in the format string
tests\test_simple.c(60): warning C4777: 'fprintf' : format string '%.*s' requires an argument of type 'int', but variadic argument 2 has type 'std::size_t'
tests\test_simple.c(60): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
tests\test_simple.c(60): note: this argument is used as a precision
tests\test_simple.c(60): note: the sizes of types 'std::size_t' and 'int' might differ on other platforms
```