scp: fix missing cast for targets without large file support
E.g. on 32-bit Linux.

```
/home/runner/work/libssh2/libssh2/src/scp.c: In function ‘scp_recv’:
/home/runner/work/libssh2/libssh2/src/scp.c:765:23: error: conversion from ‘libssh2_int64_t’ {aka ‘long long int’} to ‘__off_t’ {aka ‘long int’} may change value [-Werror=conversion]
  765 |         sb->st_size = session->scpRecv_size;
      |                       ^~~~~~~
```
Ref: https://github.com/libssh2/libssh2/actions/runs/5126803482/jobs/9221746299?pr=1054#step:12:51

Closes #1060