openssl: fix conditions for enabling AES support
Require LibreSSL 3.6.0+. Older versions fail to compile with this:
```
src/openssl.c:861:40: error: use of undeclared identifier 'EVP_CTRL_AEAD_SET_IV_FIXED'
  861 |         rc |= !EVP_CIPHER_CTX_ctrl(*h, EVP_CTRL_AEAD_SET_IV_FIXED, -1, iv);
      |                                        ^
```

Also fix the guard after its last update to behave as intended.

Follow-up to cea796fc2dd79aa56d56a5e6b0ded36662c6f094 #1668