fix openssl regression
when built with wolfSSL. Not sure why it didn't come up
with OpenSSL 1.x.

```
../src/openssl.c:3852:19: error: variable 'sslError' set but not used [-Werror,-Wunused-but-set-variable]
    unsigned long sslError;
                  ^
```

Regression from 097c8f0dae558643d43051947a1c35b65e1c5761