examples: include `select.h` again, where select() is used
Follow-up to a683133dfe96de126194f58f183131a84c7d36a2 #999

Also causing this strict ISO builds:
```
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:67:20: error: variable has incomplete type 'struct timeval'
   67 |     struct timeval tv;
      |                    ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:67:12: note: forward declaration of 'struct timeval'
   67 |     struct timeval tv;
      |            ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:249:9: error: use of undeclared identifier 'fd_set'
  249 |         fd_set fds;
      |         ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:250:9: error: call to undeclared function 'FD_ZERO'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  250 |         FD_ZERO(&fds);
      |         ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:250:18: error: use of undeclared identifier 'fds'
  250 |         FD_ZERO(&fds);
      |                  ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:255:9: error: call to undeclared function 'FD_SET'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  255 |         FD_SET(forwardsock, &fds);
      |         ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:255:30: error: use of undeclared identifier 'fds'
  255 |         FD_SET(forwardsock, &fds);
      |                              ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:261:14: error: call to undeclared function 'select'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  261 |         rc = select((int)(forwardsock + 1), &fds, NULL, NULL, &tv);
      |              ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:261:46: error: use of undeclared identifier 'fds'
  261 |         rc = select((int)(forwardsock + 1), &fds, NULL, NULL, &tv);
      |                                              ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:270:18: error: call to undeclared function 'FD_ISSET'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  270 |         if(rc && FD_ISSET(forwardsock, &fds)) {
      |                  ^
/home/runner/work/libssh2/libssh2/example/direct_tcpip.c:270:41: error: use of undeclared identifier 'fds'
  270 |         if(rc && FD_ISSET(forwardsock, &fds)) {
      |                                         ^
10 errors generated.
```
https://github.com/libssh2/libssh2/actions/runs/24107290427/job/70333563236