wincng: allow disabling more crypto features
- honor `LIBSSH2_NO_*` macros.
- disable more RSA code.
- disable RC4, DES3.
- merge !RSA + !DSA `#if` blocks.

Notes:
- DH needs RSA algo, do not disable algo slot.
- disabling both RSA and DSA results in a broken build:
  ```
  src/userauth.c: undefined reference to `ssh2_pub_priv_keyfile'
  src/userauth.c: undefined reference to `ssh2_pub_priv_keyfilememory'
  ```
- `hAlgChacha20` is declared and referenced, but not
  initialized, or used.

Closes #1985