wincng: check bignum length and resize result in `wcng_bn_mod_exp()`
- check `wcng_bn_resize()` success. The only call where this check was
  missing.

- check if bignum length is non-zero before calling resize.
  To fix this clang-tidy warning after applying pending PR #2645:
  ```
  src/wincng.c:157:14: error: Call to 'realloc' has an allocation size of 0 bytes [clang-analyzer-optin.portability.UnixAPI,-warnings-as-errors]
    157 |     bignum = realloc(bn->bignum, length);
        |              ^
  [...]
  src/wincng.c:255:27: note: Value assigned to 'offset'
    255 |                     ret = BCryptEncrypt(hKey, bignum, length, NULL, NULL, 0,
        |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    256 |                                         r->bignum, (ULONG)r->length, &offset,
        |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    257 |                                         BCRYPT_PAD_NONE);
        |                                         ~~~~~~~~~~~~~~~~
  [...]
  src/wincng.c:259:21: note: Taking true branch
    259 |                     if(BCRYPT_SUCCESS(ret))
        |                     ^
  src/wincng.c:260:43: note: Passing value via 2nd parameter 'length'
    260 |                         wcng_bn_resize(r, offset);
        |                                           ^~~~~~
  src/wincng.c:260:25: note: Calling 'wcng_bn_resize'
    260 |                         wcng_bn_resize(r, offset);
        |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
  [...]
  src/wincng.c:157:14: note: Call to 'realloc' has an allocation size of 0 bytes
    157 |     bignum = realloc(bn->bignum, length);
        |              ^                   ~~~~~~
  ```
  Ref: https://github.com/libssh2/libssh2/actions/runs/37005655840/job/110833185040?pr=2645#step:8:62
  Bug: https://github.com/libssh2/libssh2/pull/2645#issuecomment-5954426479

Closes #2649