pem: add hack to build without MD5 crypto-backend support
The Homebrew wolfSSL build comes with MD5 support disabled. This is
expected to become the norm with other builds. FIPS also requires MD5
disabled.

The same hack was deleted recently from hostkey.c: ad6aae302aaec84afbfacf0c1dfdc446d46eaf21

A better fix would be to guard the MD5 logic with our LIBSSH2_MD5 macro.

```
pem.c:214:32: error: use of undeclared identifier 'MD5_DIGEST_LENGTH'; did you mean 'SHA_DIGEST_LENGTH'?
        unsigned char secret[2*MD5_DIGEST_LENGTH];
                               ^~~~~~~~~~~~~~~~~
                               SHA_DIGEST_LENGTH
```

Regression from 386e012292a96fcf0dc6861588397845df0aba2c