move std headers first to not interfere with local redefs on Windows
```
sftp_RW_nonblock.c
  sftp_append.c
D:\a\libssh2\libssh2\example\scp_write.c(88,14): error C2220: the following warning is treated as an error [D:\a\libssh2\libssh2\bld\example\libssh2-example-all.vcxproj]
D:\a\libssh2\libssh2\example\scp_write.c(88,14): warning C4996: '_fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details. [D:\a\libssh2\libssh2\bld\example\libssh2-example-all.vcxproj]
D:\a\libssh2\libssh2\example\scp_write_nonblock.c(136,14): error C2220: the following warning is treated as an error [D:\a\libssh2\libssh2\bld\example\libssh2-example-all.vcxproj]
D:\a\libssh2\libssh2\example\scp_write_nonblock.c(136,14): warning C4996: '_fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details. [D:\a\libssh2\libssh2\bld\example\libssh2-example-all.vcxproj]
  sftp_mkdir.c
```
https://github.com/libssh2/libssh2/actions/runs/30801337534/job/91646352000?pr=2498