configure.ac: add crypto libs late
Otherwise crypto libs are linked for feature tests, which may
cause unwanted detections. For example LibreSSL publishes the
function `explicit_bzero()`, which masks the system alternative,
e.g. memset_s() on macOS. Then when trying to compile libssh2,
the declaration is missing:

```
bcrypt_pbkdf.c:93:5: error: implicit declaration of function 'explicit_bzero' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    _libssh2_explicit_zero(ciphertext, sizeof(ciphertext));
    ^
../src/misc.h:50:43: note: expanded from macro '_libssh2_explicit_zero'
                                          ^
```

Fix this by adding crypto libs to `LIBS` at the very end of the
configuration process.

Regression from 4f0f4bff5a92dce6a6cd7a5600a8ee5660402c3f