try windows cmake consumption tests
ln not available on Windows:
```
+ rm -rf libssh2
+ ln -s ../.. libssh2
ln: failed to create symbolic link 'libssh2': Too many levels of symbolic links
Error: Process completed with exit code 1.
```
https://github.com/libssh2/libssh2/actions/runs/14624901570/job/41033968722#step:6:31

MSYS2 wolfssl missing openssl compat