openssl: fix dereferencing ambiguity potentially causing build failure
When dereferencing from *aes_ctr_cipher, being a pointer itself,
ambiguity can occur with compiler and build can fail reporting:
openssl.c:574:20: error: ‘*aes_ctr_cipher’ is a pointer; did you mean to use ‘->’?
     *aes_ctr_cipher->nid = type;

Sorround every *aes_ctr_cipher-> occurence with paranthesis like this
(*aes_ctr_cipher)->

Signed-off-by: Giulio Benetti <giulio.benetti@micronovasrl.com>