agent: fix unused macro compiler warnings in UWP non-unity builds
```
src/agent.c:48:9: error: macro is not used [-Wunused-macros]
   48 | #define AGENT_MAX_MSGLEN  8192
      |         ^
src/agent.c:46:9: error: macro is not used [-Wunused-macros]
   46 | #define OPENSSH_AUTH_SOCK "SSH_AUTH_SOCK"
      |         ^
```

Follow-up to 49abb5e5688f8ec7894f82564afa65379caaea24 #2313

Closes #2325