am: disable -Wleading-whitespace=spaces. incompat with AC_FUNC_ALLOCA and autoconf
```
In file included from ../../src/libssh2_setup.h:21,
                 from ../../src/libssh2_priv.h:56,
                 from ../../src/bcrypt_pbkdf.c:20:
../src/libssh2_config.h:190:8: error: whitespace other than spaces in leading whitespace [-Werror=leading-whitespace=]
  190 |         STACK_DIRECTION > 0 => grows toward higher addresses
../src/libssh2_config.h:191:8: error: whitespace other than spaces in leading whitespace [-Werror=leading-whitespace=]
  191 |         STACK_DIRECTION < 0 => grows toward lower addresses
../src/libssh2_config.h:192:8: error: whitespace other than spaces in leading whitespace [-Werror=leading-whitespace=]
  192 |         STACK_DIRECTION = 0 => direction of growth unknown */
In file included from ../../src/libssh2_setup.h:21,
                 from ../../src/libssh2_priv.h:56,
                 from ../../src/channel.c:42:
../src/libssh2_config.h:190:8: error: whitespace other than spaces in leading whitespace [-Werror=leading-whitespace=]
  190 |         STACK_DIRECTION > 0 => grows toward higher addresses
../src/libssh2_config.h:191:8: error: whitespace other than spaces in leading whitespace [-Werror=leading-whitespace=]
  191 |         STACK_DIRECTION < 0 => grows toward lower addresses
../src/libssh2_config.h:192:8: error: whitespace other than spaces in leading whitespace [-Werror=leading-whitespace=]
  192 |         STACK_DIRECTION = 0 => direction of growth unknown */
In file included from ../../src/libssh2_setup.h:21,
                 from ../../src/libssh2_priv.h:56,
                 from ../../src/agent.c:42:
```
https://github.com/libssh2/libssh2/actions/runs/26981291885/job/79620874898?pr=1972

libssh2_config.h (see tabs):
```
/* Define to the version of this package. */

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at runtime.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if all of the C89 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
```