transport: fix potential NULL ptr deref 2
Assessment by @willco007:
Warning: `local_mac->mac_len` could potentially be hit if a crypt method
was defined incorrectly. However, none of the crypt methods can hit this
in reality. NULL check here is fine, it will prevent the crash and just
fail to encrypt the value.

```
src/transport.c:1241:31: error: Access to field 'mac_len' results in a dereference of a null pointer (loaded from variable 'local_mac') [clang-analyzer-core.NullDereference,-warnings-as-errors]
 1241 |                 int authlen = local_mac->mac_len;
      |                               ^~~~~~~~~
```