wincng: fix potentially unused macros
```
src/wincng.c:79:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
   79 | #define PEM_ECDSA_HEADER "-----BEGIN OPENSSH PRIVATE KEY-----"
      |         ^
src/wincng.c:80:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
   80 | #define PEM_ECDSA_FOOTER "-----END OPENSSH PRIVATE KEY-----"
      |         ^
```