openssl: fix unused static function
```
../../src/openssl.c:247:1: error: unused function '_libssh2_swap_bytes' [-Werror,-Wunused-function]
_libssh2_swap_bytes(unsigned char *buf, unsigned long len)
^
```

Detected now that openssl.c is no longer #included.